### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by drakezhard** [bensu/om-intermediate-tut#4]
```
(defn create-class [params]
    {:status 500})
```

Should be

```
(defn create-class [params]
  (let [db    (d/db conn)
        id    (:class/id params)
        title (:class/title params)]
    (d/transact conn [[:db/add id :class/title title]])
        (generate-response {:status :ok})))
```

I don't know how om-sync works so this might be a non issue. The only thing I'm doing different is using datomic-pro with postgresql.

**Comment by bensu** [comment]
Are you trying this from this "final code template" or are you halfway in the tutorial? If so, can you point me to where you are in the tutorial?

**Comment by drakezhard** [comment]
From the final code template.

**Comment by bensu** [comment]
That code is not meant to work. If you read under [Updating the Server](https://github.com/omcljs/om/wiki/Intermediate-Tutorial#updating-the-server):

> We're also going to add a handler for creating classes but we're going to return a 500 for now to demonstrate some neat properties of Om

and then under [Updating the Client](https://github.com/omcljs/om/wiki/Intermediate-Tutorial#updating-the-client)

> We also want to allow people to add classes. We know that the back end doesn't support this but we'll try it on the front end anyway to demonstrate the capabilities of om-sync.

Since you got it working, you could add an appendix to the original tutorial explaining your solution.
